server:
  port: 9001

spring:
  threads:
    virtual:
      enabled: true

  mvc:
    throw-exception-if-no-handler-found: true
    log-request-details: true
  web:
    resources:
      add-mappings: false

  datasource:
    url: jdbc:postgresql://localhost:5433/auth
    username: auth
    password: authpassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 80
      minimum-idle: 80
      connection-timeout: 2000
      pool-name: authPool

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        generate_statistics: false
        session:
          events:
            log: false

session:
  expiration: 3600


management:
  # Individual endpoint settings (singular)
  endpoint:
    web:
      exposure:
        include: health,metrics,prometheus
    health:
      show-details: always
      group:
        liveness:
          show-details: always
        readiness:
          show-details: always
        custom:
          include: [db, ssl]
    env:
      show-values: always
    configprops:
      show-values: always

  # Global exposure settings (plural)
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    tags:
      application: auth
  info:
    env:
      enabled: true

logging:
  level:
    com.onlineshop.auth: INFO
    org.springframework.web: TRACE
    org.hibernate.SQL: WARN
    org.hibernate.SQL_SLOW: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.hibernate.session.metrics: WARN
    org.hibernate.stat: WARN
    org.hibernate.stat.internal.StatisticsImpl: WARN
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [requestId=%X{requestId}] - %msg%n"

---
spring:
  config:
    activate:
      on-profile: hibernate-troubleshooting
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        session:
          events:
            log: true
            LOG_QUERIES_SLOWER_THAN_MS: ${auth.troubleshooting.hibernate.slow-query-threshold-ms:100}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.SQL_SLOW: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.session.metrics: DEBUG
    org.hibernate.stat: DEBUG
    org.hibernate.stat.internal.StatisticsImpl: DEBUG
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: DEBUG
